replicaCount: 1

image:
  repository: registry.digitalocean.com/gaiters-cafes/av-api
  tag: "1723997585"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

# ingress:
#   enabled: false
#   name: ""
#   className: ""
#   annotations: {}
#   hosts:
#     - host: chart-example.local
#       paths: []
#   tls: []


