name: Build Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
    - name: Build the Docker image
      working-directory: ./app
      run: podman build . --file Containerfile --tag my-image-name:$(date +%s)
