name: Build Image CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'app/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
    - name: Build the OCI image
      working-directory: ./app
      run: podman build . --file Containerfile --tag my-image-name:$(date +%s)
