name: Run Pytest

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  test:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies
      working-directory: ./app
      run: |
        poetry install

    - name: Create .config file with secrets
      working-directory: ./app
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" > .config
        echo "LOG_LEVEL=${{ secrets.LOG_LEVEL }}" >> .config

    - name: Run Pytest
      working-directory: ./app
      run: |
        poetry run pytest -v
